source 'https://cdn.cocoapods.org/'

platform :ios, "9.0"


post_install do |installer|
    # 需要指定swift编译版本的第三方的名称
    myTargets = ['TPPDF', 'Quick','Nimble']
    installer.pods_project.targets.each do |target|
        if myTargets.include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.2'
            end
        end
    end
end

use_frameworks!

target "TPPDF_Example" do
    pod "TPPDF", :path => "../"

	target "TPPDF_Tests" do
        inherit! :search_paths

        pod "Quick"
        pod "Nimble"
    end
end
