source 'https://cdn.cocoapods.org/'

platform :ios, "9.0"

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end

use_frameworks!

target "TPPDF_Example" do
    pod "TPPDF", :path => "../"

    target "TPPDF_Tests" do
        inherit! :search_paths

        pod "Quick"
        pod "Nimble"
    end
end
